- name: Create Goapp image
  hosts: localhost
  tasks:
  - name: Build image
    docker_image:
      path: /vagrant/docker-goapp
      name: goapp
- name: Create Goapp container
  hosts: localhost
  tasks:
  - name: Goapp container
    docker_container:
      name: goapp
      image: goapp
      state: started
      ports:
      - "80:8080"
      volumes:
      - ./docker-goapp:/docker-goapp
      tty: true
      detach: true

# https://github.com/phase2/docker-https-proxy
- name: Create HTTPS Proxy container
  hosts: localhost
  tasks:
  - name: Proxy container
    docker_container:
      name: proxy
      image: outrigger/https-proxy:1.0
      state: started
      ports:
      - "443:443"
      env:
        UPSTREAM_DOMAIN: "192.168.33.10"
        UPSTREAM_PORT: "80"
      tty: true
      detach: true
