---
# tasks file for /etc/ansible/roles/deploy-goapp

- name: Build goapp image
  docker_image:
    path: /vagrant/docker-goapp
    name: goapp
    source: build
- name: Run Goapp container
  docker_container:
    name: goapp
    image: goapp
    state: started
    ports:
    - "80:8080"
    volumes:
    - /vagrant/docker-goapp:/docker-goapp
    tty: true
    detach: true